### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by dheera** [OpenBuilds/firmware#2]
Hi,
Is the source code for the Interface firmware available? Some feature requests:

- Long filenames

- Ability to list, delete, and overwrite files via wifi upload

Thanks!

**Comment by petervanderwalt** [comment]
it is not open source sorry.

**Comment by dheera** [comment]
Okay, I'd urge you to reconsider that ... ? Why is Openbuilds Control open-source but not the Interface?
